AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdaetl37:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 10240
      Timeout: 900
      Role: 'arn:aws:iam::533897051601:role/robomaker_students'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 1 * ? *)
      Environment:
        Variables:
          DB_NAME: datalake1
          ENDPOINT: datalake1.cnemzbdfnjko.us-east-1.rds.amazonaws.com
          PASSWORD: '1234567890'
          PORT: '5432'
          USERNAME: lisa
      Layers:
        - 'arn:aws:lambda:us-east-1:533897051601:layer:pandas_layer:2'
