AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lamdatwitteretl:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 150
      Timeout: 899
      Role: 'arn:aws:iam::529282022069:role/LabRole'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(7 days)
      Environment:
        Variables:
          ACCES_TOKEN_SECRET: dMM9yHiaCU8kehKNiJvKtF9dkgRgNupcX63Dcf4f8GH2l
          DB_NAME: datalakeTwitter
          ENDPOINT: datalaketwitter.c16p7bc6xhi2.us-east-1.rds.amazonaws.com
          USERNAME: nadine
          CONSUMER_KEY: tLlNyxv25Z4P6iDpNYohcnvQP
          CONSUMER_SECRET: NuNIcft96X61AuAIxvEUdH3AOjenRf86V2TVClw2iyclila9Kn
          PASSWORD: '30101995'
          BEARER_TOKEN: >-
            AAAAAAAAAAAAAAAAAAAAAL1JaAEAAAAAHkzB8G75rhf%2FltnxJYxnfZSAvKM%3Dw9qHHYkaZgb5QHgiwQxHEu1bxPwr57locRfheMP2HS2NvpqkBA
          ACCESS_TOKEN: 1501850566456193027-XeRgm19kD8EdNqt0OXxIdw5F2Cj0Fx
      Layers:
        - 'arn:aws:lambda:us-east-1:529282022069:layer:project_layer:1'
